[[permission]]
identifier = "document-r"
commands.allow = ["load_content", "load_meta"]

[[permission]]
identifier = "document-w"
commands.allow = ["save_content", "save_meta", "create_new_work"]

[[permission]]
identifier = "document-default"
permissions = [
    "document-r",
    "document-w"
]